name: Test Schedule 2

on:
    schedule:
        - cron: "*/2 * * * *"
    workflow_dispatch:

jobs:
    test-log:
        name: Console log test 2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run index.js
              run: node index.js
